// UI Components will be added here
// This file serves as a barrel export for shadcn/ui components

// Example exports (to be added when components are installed):
// export { Button } from './button';
// export { Input } from './input';
// export { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from './card';

// Placeholder export to prevent empty module error
export const UI_COMPONENTS_PLACEHOLDER =
  'UI components will be added here';

// Core UI Components - Generated by shadcn/ui
// These components follow accessibility and responsiveness best practices

export { Button, buttonVariants } from './button';
export { Input } from './input';
export { Label } from './label';
export {
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardDescription,
  CardContent,
  CardAction,
} from './card';
export { Alert, AlertTitle, AlertDescription } from './alert';
export { ThemeToggle } from './ThemeToggle';
export {
  Sheet,
  SheetTrigger,
  SheetClose,
  SheetContent,
  SheetHeader,
  SheetFooter,
  SheetTitle,
  SheetDescription,
} from './sheet';

// Re-export utility function for component composition
export { cn } from '@/lib/utils';

// Demo component for showcasing all UI components
export { ComponentDemo } from './demo';
